# Generated by Django 5.0 on 2023-12-31 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='files/images')),
                ('title_description', models.TextField(blank=True, null=True)),
                ('video_id', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=500)),
                ('time', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=500)),
                ('start', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterCourseForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pay', 'Pay'), ('waiting', 'Waiting'), ('undone', 'Undone')], default='waiting', max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LiveCourses.livecourse')),
            ],
        ),
    ]
