# Generated by Django 5.0 on 2023-12-31 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LiveCourses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisterCourseForm',
            new_name='Enrollment',
        ),
    ]
