# Generated by Django 5.0 on 2023-12-31 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LiveCourses', '0003_livecourse_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livecourse',
            name='creator',
        ),
    ]
