# Generated by Django 5.0 on 2023-12-31 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveCourses', '0004_remove_livecourse_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='livecourse',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='livecourse', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
