# Generated by Django 5.0 on 2024-01-15 02:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_comment_course_course_sections_course_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='episode_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
