# Generated by Django 5.0 on 2024-01-15 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_episode_episode_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='episode_uuid',
        ),
    ]
