# Generated by Django 5.0 on 2024-01-15 21:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0005_usercourse'),
        ('Quiz', '0016_alter_exam_id_alter_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='episode_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.CreateModel(
            name='EpisodeQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Exam Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('questions', models.ManyToManyField(related_name='episodequiz', to='Quiz.question')),
            ],
        ),
        migrations.DeleteModel(
            name='ExamVideo',
        ),
    ]
