# Generated by Django 5.0 on 2024-01-15 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0006_episode_episode_uuid_episodequiz_delete_examvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='exam',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Courses.episodequiz'),
            preserve_default=False,
        ),
    ]
