# Generated by Django 5.0 on 2024-01-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0007_episode_exam'),
        ('Quiz', '0016_alter_exam_id_alter_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesection',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='episodequiz',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='episodequiz',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='episodequiz', to='Quiz.question'),
        ),
        migrations.AlterField(
            model_name='episodequiz',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Exam Title'),
        ),
    ]
