# Generated by Django 5.0 on 2024-01-17 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0008_alter_coursesection_description_alter_episode_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='serial_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='episode',
            name='exam',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Courses.episodequiz'),
        ),
    ]
