# Generated by Django 5.0 on 2023-12-31 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_questioncategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_content', models.TextField(verbose_name='Question Content')),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='question_images/', verbose_name='Question Image')),
                ('question_video', models.FileField(blank=True, null=True, upload_to='question_videos/', verbose_name='Question Video')),
                ('option_A', models.CharField(max_length=500)),
                ('option_B', models.CharField(max_length=500)),
                ('option_C', models.CharField(blank=True, max_length=500)),
                ('option_D', models.CharField(blank=True, max_length=500)),
                ('time_to_answer', models.IntegerField(default=60, verbose_name='Time to Answer (in seconds)')),
                ('marks', models.IntegerField(default=5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Quiz.questioncategory')),
            ],
        ),
    ]
