# Generated by Django 5.0 on 2023-12-31 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_examsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubmission',
            name='exam',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='Quiz.exam'),
            preserve_default=False,
        ),
    ]
