# Generated by Django 5.0 on 2023-12-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0007_examsubmission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubmission',
            name='score',
            field=models.FloatField(default=0, verbose_name='Exam Score'),
        ),
    ]
