# Generated by Django 5.0 on 2023-12-31 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0008_examsubmission_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamSubmission',
        ),
    ]
