# Generated by Django 5.0 on 2023-12-31 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0009_delete_examsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='exams',
            field=models.ManyToManyField(related_name='questions', to='Quiz.exam'),
        ),
    ]
