# Generated by Django 5.0 on 2023-12-31 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0012_studentanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsubmission',
            name='created_new_exam',
        ),
        migrations.DeleteModel(
            name='StudentAnswer',
        ),
    ]
