# Generated by Django 5.0 on 2023-12-31 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0013_remove_examsubmission_created_new_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubmission',
            name='wrong_answers',
            field=models.ManyToManyField(blank=True, to='Quiz.question'),
        ),
    ]
