# Generated by Django 5.0 on 2024-01-16 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0016_alter_exam_id_alter_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(choices=[('A', 1), ('B', 2), ('C', 3), ('D', 4)], max_length=1),
        ),
    ]
