# Generated by Django 5.0 on 2024-01-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0018_alter_question_correct_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1),
        ),
    ]
