# Generated by Django 5.0 on 2024-01-21 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0021_remove_question_marks_remove_question_time_to_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userexam',
            old_name='course',
            new_name='exam',
        ),
    ]
