# Generated by Django 5.0 on 2024-01-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0022_rename_course_userexam_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_video_youtube',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
