# Generated by Django 5.0 on 2024-01-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0023_alter_question_question_video_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='time_to_answer',
            field=models.IntegerField(default=60, verbose_name='Time to Answer (in seconds)'),
        ),
    ]
