# Generated by Django 5.0 on 2024-01-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0024_exam_time_to_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='time_to_answer',
            field=models.IntegerField(default=60, verbose_name='Time to Answer '),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_content',
            field=models.TextField(blank=True, null=True, verbose_name='Question Content'),
        ),
    ]
