# Generated by Django 5.0 on 2024-01-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0025_alter_exam_time_to_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexam',
            name='tries',
            field=models.FloatField(default=1, verbose_name='tries'),
        ),
    ]
