# Generated by Django 5.0 on 2023-12-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('S', 'Student '), ('T', 'Teacher'), ('M', 'Manager')], max_length=1),
        ),
    ]
