# Generated by Django 5.0 on 2023-12-31 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('S', 'Student'), ('T', 'Teacher'), ('M', 'Manager')], help_text='The type of user.', max_length=1),
        ),
    ]
